version: '3.9'

services:

  backend:
    build:
      dockerfile: Dockerfile.development
    image: spring_boot
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/whimdb

  postgres:
    restart: always
    image: postgres:13.3
    environment:
      POSTGRES_DB: "whimdb"
      POSTGRES_USER: "whim"
      POSTGRES_PASSWORD: "hello"
    ports:
      - "5432:5432"
