version: '3.9'

services:
  postgres:
      restart: always
      image: postgres:13.3
      environment:
        POSTGRES_DB: "whimdb"
        POSTGRES_USER: "whim"
        POSTGRES_PASSWORD: "hello"
      ports:
        - "5432:5432"
